version: 1.0.0

description: |-
  Vault storage template generator.

requires:
  fbl: '>=1.8.0'
  applications:
   - yarn

pipeline:
  '--':
    - ctx:
        '$.versions':
          inline: 
            crypto: 1.1.0
            fbl: 1.8.0

    <$ if (!ctx.destination) { $>
    - prompt:
        message: 'Where do you want to setup the vault?'
        default: <%- cwd %>
        assignResponseTo:
          ctx: $.destination
    <$ } $>

    <$ [
      'package.json',      
    ].forEach(path => { $>
    - '->':
        contentFromFile: templates/<$- path $>
        path: <%- $.fs.getAbsolutePath(ctx.destination, cwd) %>/<$- path $>
    <$ }); $>

    <$ [
      'decrypt.yml',
      'encrypt.yml',      
      '.gitignore',      
    ].forEach(path => { $>
    - cp:
        from: templates/<$- path $>
        to: <%- $.fs.getAbsolutePath(ctx.destination, cwd) %>/<$- path $>
    <$ }); $>

    - exec:
        command: yarn
        args:
          - install
        wd: <%- ctx.destination %>
        options:
          verbose: true
