version: 1.0.0

requires:
  fbl: '>=1.4.0 <2.0.0'
  plugins:
    '@fbl-plugins/crypto': '1.0.1'

description: |-
  Copy all files and folders from "encrypted" to "decrypted" folder and decrypt them.

pipeline:
  '--':
    <$ if (!secrets.password) { $>
    - prompt:
        message: 'Please enter the password:'
        password: true
        assignResponseTo:
          secrets: $.password
    <$ } $>

    - try:
        action:
          '--':
            - rm: decrypted/

    - cp:
        from: encrypted/
        to: decrypted/

    - find:
        include:
          - decrypted/**/*
        result:
          assignTo: '$.ctx.files'
    
    - each:
        of: $ref:ctx.files
        action:
          decrypt:
            password: $ref:secrets.password
            file: $ref:iteration.value

