version: 1.0.0

requires:
  fbl: '>=1.8.0 <2.0.0'
  plugins:
    '@fbl-plugins/crypto': '1.1.0'

description: |-
  Copy all files and folders from "decrypted" to "encrypted" folder and encrypt them.

pipeline:  
  '--':
    <$ if (!secrets.password) { $>
    - prompt:
        message: 'Please enter the password:'
        password: true
        assignResponseTo:
          secrets: $.password

    - prompt:
        message: 'Please enter the password once again:'
        password: true
        assignResponseTo:
          secrets: $.passwordConfirmation
    
    - '?':
        value: "<%- secrets.passwordConfirmation == secrets.password %>"
        is:
          false:
            error: 'Passwords do not match'
    <$ } $>

    - try:
        action:
          '--':
            - rm: encrypted/

    - cp:
        from: decrypted/
        to: encrypted/

    - find:
        include:
          - encrypted/**/*
        result:
          assignTo: '$.ctx.files'
    
    - each:
        of: $ref:ctx.files
        action:
          encrypt:
            password: $ref:secrets.password
            file: $ref:iteration.value            
  
